# Generated by Django 3.0 on 2019-12-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('player_names', models.TextField(blank=True)),
                ('city', models.CharField(max_length=250)),
                ('team_manager', models.CharField(max_length=250)),
                ('team_manager_phonenumber', models.CharField(max_length=250)),
                ('team_manager_cnic', models.CharField(max_length=250)),
                ('team_captain', models.CharField(max_length=250)),
                ('team_captain_phonenumber', models.CharField(max_length=250)),
                ('extra_remarks', models.TextField(blank=True)),
            ],
        ),
    ]
